### ISSUE TITLE
Type errors in interfaces definition

### ISSUE THREAD

**Issue by andrejleitner** [remojansen/InversifyJS#1422]
## Expected Behavior
Typescript compilation to work smoothly.

## Current Behavior
```
node_modules/inversify/lib/interfaces/interfaces.d.ts:275:10 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

275         [propertyNameOrArgumentIndex: string | symbol]: Metadata[];
```

## Context
Appeared after the version upgrade: `5.1.1` > `6.0.1`

## Your Environment
* Version used: 6.0.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 16.13.1
* Operating System and version (desktop or mobile): N.A.
* Link to your project: N.A.

**Comment by icco** [comment]
We're also seeing this.

**Comment by notaphplover** [comment]
Hi @andrejleitner , @icco. Are you using `skipLibCheck` typescript option? It seems you may be using Typescript versions which does not support `symbol` index signatures. Symbol index signatures are supported since [Typescript 4.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#symbol-and-template-string-pattern-index-signatures)

Can you provide a minimal example to recreate this. At first I would hazard to say your typescript projects should not rely on certain versions of third party typescript projects, so `skipLibCheck` is often a good way to go

**Comment by andrejleitner** [comment]
Currently using `typescript@4.3.5`.

**Comment by jkhmtx** [comment]
@notaphplover 's recommendation to use `skipLibCheck` in your `tsconfig.json` is a great way to proceed in case it is not possible for you to upgrade your Typescript minor version to `v4.4`.

I believe that this is something for which we would not backport a "fix" since there is a userland workaround. I recommend closing this issue.
