### ISSUE TITLE
Newable interface doesn't accept arguments

### ISSUE THREAD

**Issue by andrejleitner** [remojansen/InversifyJS#1423]
## Expected Behavior
Constructor arguments are allowed.

## Current Behavior
```ts
export type Newable<T> = new (...args: never[]) => T;
```

## Possible Solution
```ts
export type Newable<T> = new (...args: any[]) => T;
```

## Your Environment
* Version used: 6.0.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 16.13.1
* Operating System and version (desktop or mobile): N.A.
* Link to your project: N.A.

**Comment by PodaruDragos** [comment]
hello @andrejleitner. Can you provide me with an example of what you are doing so that we need to change to any.
we moved from any to never since you don't really need arguments there.

We do constructor injection in tests and all of them are passing.

If you find a way to this without `any` i would really apreciate it.

**Comment by andrejleitner** [comment]
https://github.com/inversify/InversifyJS/pull/1424#issuecomment-1023228454
