### ISSUE TITLE
Decorator[@targetName] error TS1239: Unable to resolve signature of parameter decorator when called as an expression

### ISSUE THREAD

**Issue by wangsyiiz** [remojansen/InversifyJS#1556]
## Expected Behavior
There should not be any error occurred when `@targetName` be used at constructor

## Current Behavior
` constructor(@inject("IService") @targetName("queueService") ticketQueue: IService) {
    }`

`error TS1239: Unable to resolve signature of parameter decorator when called as an expression`

## Your Environment
* Version used: 6.0.2
* Environment name and version: 16.20.2
* Operating System and version: win11
* Link to your project:

# Stack trace

**Comment by wangsyiiz** [comment]
ok, actually I found another decorator `@named` can be used in normally, but still in [documentation](https://github.com/inversify/InversifyJS/blob/master/wiki/contextual_bindings.md) it indicates to use `@targetName`, is that a wrong description?

**Comment by gustavohenke** [comment]
Both are documented, here's `@named`'s: https://github.com/inversify/InversifyJS/blob/7619dd4395516fa53f435d08f30cead349901be8/wiki/named_bindings.md

The error comes from the signature of `@targetName` not properly matching the decorator signature anymore.
It's new on Typescript 5: https://github.com/microsoft/TypeScript/issues/52435

---

That said, I don't understand the difference between `@named` and `@targetName`. `@named` seems slightly better supported, and `@targetName`'s docs mention the use of `namedConstraint`, which doesn't work because it works on a different tag.

**Comment by gustavohenke** [comment]
Created #1561 to fix this.

**Comment by notaphplover** [comment]
Hey all, sorry for the delay. I'm starting to give some love the project again. This issue should be fixed in #1586. I'll release a new version soon :)
