### ISSUE TITLE
Error: Missing required @inject or @multiInject

### ISSUE THREAD

**Issue by Maxttier** [remojansen/InversifyJS#1598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
<script lang="ts">
import { Container, inject, injectable, type interfaces } from 'inversify'
import { Component, Vue, Setup, toNative } from 'vue-facing-decorator'

container = new Container({ skipBaseClassChecks: true })
container.bind(Katana).toSelf()
container.bind(Shuriken).toSelf()
container.bind(Ninja).toSelf()

@injectable()
export class Katana {
  public hit() {
    return 'cut!'
  }
}

@injectable()
export class Shuriken {
  public throw() {
    return 'hit!'
  }
}

@injectable()
export class Ninja {
  public constructor(
    @inject(Katana) private katana: Katana,
  ) {}

  public fight() {
    return this.katana.hit()
  }
}

@Component({
})
@injectable()
class PlaygroundApp extends Vue {
  constructor(
    options: any,
    instance: any,
    @inject('Ninja')
    public ninja: Ninja
  ) {
    super(options, instance)
  }

  value!: number

  inc() {
    this.value++
  }
}
</script>

<template>
</template>
```

@Component({
})
@injectable()
class Page extends Vue {
  // get PlaygroundApp here 
}

### Steps to reproduce

Error: Missing required @inject or @multiInject annotation in: argument 0 in class PlaygroundApp.

if i use decorate it say what i decorated PlaygroundApp it multiple time.

Also i use decorate for Vue

Use  container = new Container({ skipBaseClassChecks: true })

### Expected behavior

`@inject('Ninja')    public ninja: Ninja` in constructor to work
inject one vue component in another tor work (this is not not useful in that case)

### Package version

6.0.1

### Node.js version

20.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

https://github.com/mak7an/nuxt/blob/main/app.vue

**Comment by notaphplover** [comment]
As stated in the docs, all the arguments of a service must be decorated with `@inject`, `@multiInject`, `@unmanaged` or typescript decorated metadata.

`PlaygroundApp` does not meet these requirements since no decorators are provided for `options` nor `instance` parameters and no typescript metadata will be used for `options: any` since `Object` will be the decorated metadata by typescript  and there's no way to know which service is associated to `Object`.

The behavior is the expected one. I will close the issue now, feel free to comment, if I missed anything I'll reopen it.

**Comment by mak7an** [comment]
If I add @unmanaged to options and instance will it work?
