### ISSUE TITLE
lazyInject doesn't work 

### ISSUE THREAD

**Issue by volkerrichert** [remojansen/InversifyJS#1678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

A lazy injection return undefined instead of the injected instance.

### Steps to reproduce

1. use the example from here https://github.com/inversify/inversify-inject-decorators?tab=readme-ov-file#basic-property-lazy-injection-with-lazyinject
2. run it using TS 5.5 and node 20
3. console returns false instead of true

### Expected behavior

console returns true and instance is injected

### Possible solution

the property is initialized with undefined. if this is reverted (e.g. delete it), it works

### Package version

6.1.5

### Node.js version

20.x

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by notaphplover** [comment]
Hey @volkerrichert, I had a look at the issue. Tbh I had never had a look at the binding decorators package, so it was not familiar with the internal implementation of the decorators. After having a look at them, I come with bad news.

### What's the root cause of the issue

Basically, `lazyInject` implementation updates the prototype of the class with a proxy that invokes the container resolution of the service.

So far so good, right? Let's have a look at this simple ts code:

```ts
class Foo {
    public bar!: string;
}
```

If your tsconfig have [useDefineForClassFields](https://www.typescriptlang.org/tsconfig/#useDefineForClassFields) options enabled (they are enabled by default), the transpilation would be this one:

```js
"use strict";
class Foo {
    bar;
}
```

Otherwise, the transpilation would be this one:

```js
"use strict";
class Foo {
}
```

This `useDefineForClassFields` behavior is causing the issue. Let's say we create a new Foo:

```js
const foo = new Foo();

foo.bar
```

If `Foo` has the `bar` property declaration defined, `foo.bar` is instantiated to `undefined` when `foo` is initialized and therefore, `foo.bar` is evaluated to undefined no matter what prototype proxy injection is `lazyInject` doing under the scenes.

### What to do now
Tbh, I don't see a good way of fixing this. Typescript emitting property declarations makes total sense and avoids any prototype modification to work. My cup of tea would be relying on the `inject` inversify decorator which is properly maintained and does not rely on prototype tricks.

After having a look at the internal implemetation of the library and the current state of the art, I think archiving `inversify-inject-decorators` repo and updating docs to stop promoting their usage would be my cup of tea.

I'm closing the issue as it won't be fixed in favor of stop promoting `inversify-inject-decorators`. If someone has an idea of making lazy injection work, feel free to ping me to have it a look :smiley:

@rsaz what are your thoughs about this?

**Comment by volkerrichert** [comment]
My analysis has the same result, but I doesn't know about useDefineForClassFields. So, I did expect that a bit.

One possible solution could be deleting the property in the prototype during creation of the proxy. But I'm not sure if i like that solution myself. :-)

As a workaround, I implement a getter and call a helper to get the instance.

**Comment by notaphplover** [comment]
Hey @volkerrichert

> One possible solution could be deleting the property in the prototype during creation of the proxy. But I'm not sure if i like that solution myself. :-)

I believe we cannot delete a class property declaration. I agree with you, I would prefer not to go that way.

> As a workaround, I implement a getter and call a helper to get the instance.

Why not simply relying on `@inject`? May I know a little bit about your use case?

**Comment by volkerrichert** [comment]
I have to use some lazy injections to avoid circular dependencies. Maybe i can get rid of a few of them, but not all.

**Comment by notaphplover** [comment]
I see. We could probably achieve lazy injection with a different approach. I'm thinking in a `Proxy`. The thing about circular dependencies is that there're always edge cases which cannot be solved. Consider the following sample code:

```ts
@injectable()
class A {
  readonly #foo: unknown;

  constructor(@inject(B) b: B) { this.#foo = b.foo(); }

  public foo(): unknown {
    return this.#foo;
  }
}

@injectable()
class B {
  readonly #foo: unknown;

  constructor(@inject(A) a: A) { this.#foo = a.foo(); }

  public foo(): unknown {
    return this.#foo;
  }
}
````

Which is the output of `a.foo()`? This call should throw a stack overflow exception. With this is mind:

```ts
@injectable()
class A {
  readonly #foo: unknown;

  constructor(@inject(B) b: B) { this.#foo = b.foo(); }

  public foo(): unknown {
    return this.#foo;
  }
}

@injectable()
class B {
  readonly #foo: unknown;

  constructor(@inject(A) a: A) { this.#foo = a.foo(); }

  public foo(): unknown {
    return 'foo';
  }
}
````

Which is the output of `a.foo()` now? With the right approach, it should be `'foo'`, but the only way to do this is having an understanding of both classes implementation. The proxy approach is not good enought for theses cases but it could solve some easier ones. We could probably provide an `@injectRef` which under the scenes provides a Proxy to handle circular dependency injection, but my current priority is a big refactor I'm accomplishing to give proper maintenance to the library.

Regarding your use case, I don't see an easy general purpose workaround. When I've faced circular dependencies in the past they've been smell of flaws in my design, but I'm well aware it's easier said than done. You could try to rely on `@lazyInject()` in case you cannot solve them all, but then you will have to set `useDefineForClassFields` to `false` in your typescript config to make it work.

**Comment by hosseinalipour** [comment]
It's far from perfect, but I don't have time to wait and can't disable useDefineForClassFields. I use this until the community agrees on a better solution.  

```ts
import { Container } from 'inversify';

function getLazyInjectors(container: Container) {
  const constructors = new WeakMap();
  function lazyInjectable<T extends { new (...args: any[]): object }>() {
    return (target: T) => {
      return class extends target {
        constructor(...args: any[]) {
          super(...args);
          let value: any;

          const targets = constructors.get(target);
          for (const [property, type] of targets) {
            Object.defineProperty(this, property, {
              get: function () {
                if (value === undefined) {
                  value = container.get(type);
                }
                return value;
              },
              set: function (newValue) {
                value = newValue;
              },
              enumerable: true,
              configurable: false,
            });
          }
        }
      };
    };
  }

  function lazyInject(type) {
    return function (_target, property: string) {
      const targets = constructors.get(_target.constructor) || new Map();
      targets.set(property, type);
      constructors.set(_target.constructor, targets);
    };
  }

  return { lazyInjectable, lazyInject };
}



@injectable()
@lazyInjectable()
export default class MathOps {
  @lazyInject('expensive')
  public myExpensive!: string;

  constructor(@inject('another') public cheap: any) {}

  some() {
    console.log(this.myExpensive);
  }
}

```
